name: Lint, Test, Deploy on Push

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
  Test:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
      - name: Npm Test
        run: npm test
  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Build
        run: npm run build
