name: Lint, Test, Deploy on Push

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Linting
        run: |
          npm install eslint --save-dev
          npx eslint --init
          npm run lint
  Test:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Npm Test
        run: npm test
  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build
        run: npm run build
